[package]
name = "gen-e-albums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
gostd = "0.3.10"
image = "0.24.7"
mime = "0.3.17"
mime_guess = "2.0.4"
