name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Release
      uses: manoadamro/rust-release@v1
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.repository }}
        token: ${{ secrets.GITHUBTOKEN }}
