name: Rust build

on:
  push:
    tags:
      - "*-v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo build
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/debug/gen-e-albums
